## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cnpsfinkwieuke
    password: 98a2406dd730382e31b5df0f4f3220f4017435ac00fd430782971495a9daf50d
    url: jdbc:postgresql://ec2-54-75-244-161.eu-west-1.compute.amazonaws.com/d3s3om013c51h6
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
#    generate-ddl: false
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  #      dialect: org.hibernate.dialect.MySQL5Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: me.zhulin
jwtExpiration: 86400
